name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  job:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          # no restore-keys here, so we only accept this exact version
      - run: yarn l10n:generate
      - run: COVERAGE=true yarn test
      - name: Code Coverage
        uses: codecov/codecov-action@v1
