name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
job:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: [14.x]
      - run: yarn l10n:generate
      - run: COVERAGE=true yarn test
      - name: Code Coverage
        uses: codecov/codecov-action@v1
